name: Docs
on: [push]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: demoSentinel
          environment-file: environment.yml
          auto-activate-base: false
      - run: |
          conda info
      - name: Sphinx build
        run: |
          sphinx-build -b html docs/source/ docs/build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true